[server]
# Configuración del servidor para desarrollo
address = "0.0.0.0"
port = 8501
headless = true
runOnSave = true
enableCORS = false
enableXsrfProtection = false

[browser]
# Configuración del navegador
gatherUsageStats = false

[theme]
# Tema por defecto
base = "light"

[client]
# Configuración del cliente
showErrorDetails = true 